/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.rmi.CORBA.Util;
import javax.swing.JOptionPane;
import utils.Utilitaire;

/**
 *
 * @author 1795545
 */
public class FenChaine extends javax.swing.JFrame {

    /**
     * Creates new form FenChaine
     */
    public FenChaine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtChaine = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtResultat = new javax.swing.JTextField();
        btnLonguer = new javax.swing.JButton();
        btnMajuscule = new javax.swing.JButton();
        btnInversion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traitment de Chaine");
        setResizable(false);

        jLabel1.setText("Chaine:");

        txtChaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChaineActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultat:");

        txtResultat.setEditable(false);
        txtResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultatActionPerformed(evt);
            }
        });

        btnLonguer.setText("Longueur");
        btnLonguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLonguerActionPerformed(evt);
            }
        });

        btnMajuscule.setText("Majuscule");
        btnMajuscule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMajusculeActionPerformed(evt);
            }
        });

        btnInversion.setText("Inversion");
        btnInversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChaine, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtResultat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnLonguer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMajuscule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInversion)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtResultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLonguer)
                    .addComponent(btnMajuscule)
                    .addComponent(btnInversion))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultatActionPerformed

    private void txtChaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChaineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChaineActionPerformed

    private void btnMajusculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMajusculeActionPerformed
        // TODO add your handling code here:
        try {
            if (txtChaine.getText().isEmpty()) {
                throw new NumberFormatException();
            }
            Utilitaire.modifierChaine(txtChaine);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Texte invalide et / ou champ est vide!", "Errour de saisir", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnMajusculeActionPerformed

    private void btnInversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversionActionPerformed
        // TODO add your handling code here:
        try {
            if (txtChaine.getText().isEmpty()) {
                throw new NumberFormatException();
            }
            Utilitaire.calculInversion(txtChaine);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Texte invalide et / ou champ est vide!", "Errour de saisir", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnInversionActionPerformed

    private void btnLonguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLonguerActionPerformed
        try {
            if (txtChaine.getText().isEmpty()) {
                throw new NumberFormatException();
            }
            txtResultat.setText(String.valueOf(Utilitaire.calculLangueur(txtChaine)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Texte invalide et / ou champ est vide!", "Errour de saisir", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnLonguerActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FenChaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FenChaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FenChaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FenChaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FenChaine().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInversion;
    private javax.swing.JButton btnLonguer;
    private javax.swing.JButton btnMajuscule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtChaine;
    private javax.swing.JTextField txtResultat;
    // End of variables declaration//GEN-END:variables
}
