package entity;
// Generated Jun 4, 2018 9:03:04 PM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int noclient;
     private String nomclient;
     private String notelephone;

    public Client() {
    }

	
    public Client(int noclient, String nomclient) {
        this.noclient = noclient;
        this.nomclient = nomclient;
    }
    public Client(int noclient, String nomclient, String notelephone) {
       this.noclient = noclient;
       this.nomclient = nomclient;
       this.notelephone = notelephone;
    }
   
    public int getNoclient() {
        return this.noclient;
    }
    
    public void setNoclient(int noclient) {
        this.noclient = noclient;
    }
    public String getNomclient() {
        return this.nomclient;
    }
    
    public void setNomclient(String nomclient) {
        this.nomclient = nomclient;
    }
    public String getNotelephone() {
        return this.notelephone;
    }
    
    public void setNotelephone(String notelephone) {
        this.notelephone = notelephone;
    }




}


