package entity;
// Generated Jun 4, 2018 9:03:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private int nocommande;
     private Date datecommande;
     private Integer noclient;

    public Commande() {
    }

	
    public Commande(int nocommande, Date datecommande) {
        this.nocommande = nocommande;
        this.datecommande = datecommande;
    }
    public Commande(int nocommande, Date datecommande, Integer noclient) {
       this.nocommande = nocommande;
       this.datecommande = datecommande;
       this.noclient = noclient;
    }
   
    public int getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(int nocommande) {
        this.nocommande = nocommande;
    }
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }
    public Integer getNoclient() {
        return this.noclient;
    }
    
    public void setNoclient(Integer noclient) {
        this.noclient = noclient;
    }




}


